version: 2.1

commands:
  install_java_package:
    steps:
      - run:
          name: Cài đặt java package
          command: |
            sudo apt-get update
            sudo apt-get install maven openjdk-17-jdk -y
            sudo apt-get install redis
            sudo redis-server --daemonize yes
jobs:

  crawl-ets-toeic-2019-test-10-ets-toeic-2022-test-10:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 0
      CRAWL_TO: 1
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 0 - 1 - ets-toeic-2019-test-10-ets-toeic-2022-test-10"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-4-ets-toeic-2022-test-9:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 2
      CRAWL_TO: 3
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 2 - 3 - ets-toeic-2020-test-4-ets-toeic-2022-test-9"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-5-ets-toeic-2021-test-5:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 4
      CRAWL_TO: 5
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 4 - 5 - ets-toeic-2020-test-5-ets-toeic-2021-test-5"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-8-ets-toeic-2020-test-6:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 6
      CRAWL_TO: 7
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 6 - 7 - ets-toeic-2022-test-8-ets-toeic-2020-test-6"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-7-ets-toeic-2020-test-7:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 8
      CRAWL_TO: 9
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 8 - 9 - ets-toeic-2022-test-7-ets-toeic-2020-test-7"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-6-ets-toeic-2020-test-8:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 10
      CRAWL_TO: 11
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 10 - 11 - ets-toeic-2022-test-6-ets-toeic-2020-test-8"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-10-ets-toeic-2020-test-9:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 12
      CRAWL_TO: 13
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 12 - 13 - ets-toeic-2020-test-10-ets-toeic-2020-test-9"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-1-ets-toeic-2019-test-8:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 14
      CRAWL_TO: 15
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 14 - 15 - ets-toeic-2022-test-1-ets-toeic-2019-test-8"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2021-test-2-ets-toeic-2022-test-5:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 16
      CRAWL_TO: 17
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 16 - 17 - ets-toeic-2021-test-2-ets-toeic-2022-test-5"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2018-test-5-ets-toeic-2019-test-9:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 18
      CRAWL_TO: 19
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 18 - 19 - ets-toeic-2018-test-5-ets-toeic-2019-test-9"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-1-ets-toeic-2021-test-1:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 20
      CRAWL_TO: 21
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 20 - 21 - ets-toeic-2020-test-1-ets-toeic-2021-test-1"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-4-ets-toeic-2019-test-6:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 22
      CRAWL_TO: 23
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 22 - 23 - ets-toeic-2022-test-4-ets-toeic-2019-test-6"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-2-ets-toeic-2021-test-4:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 24
      CRAWL_TO: 25
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 24 - 25 - ets-toeic-2020-test-2-ets-toeic-2021-test-4"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-3-ets-toeic-2019-test-7:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 26
      CRAWL_TO: 27
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 26 - 27 - ets-toeic-2022-test-3-ets-toeic-2019-test-7"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2020-test-3-ets-toeic-2021-test-3:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 28
      CRAWL_TO: 29
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 28 - 29 - ets-toeic-2020-test-3-ets-toeic-2021-test-3"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2022-test-2-ets-toeic-2018-test-2:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 30
      CRAWL_TO: 31
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 30 - 31 - ets-toeic-2022-test-2-ets-toeic-2018-test-2"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2019-test-4-ets-toeic-2018-test-1:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 32
      CRAWL_TO: 33
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 32 - 33 - ets-toeic-2019-test-4-ets-toeic-2018-test-1"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2019-test-5-ets-toeic-2018-test-4:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 34
      CRAWL_TO: 35
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 34 - 35 - ets-toeic-2019-test-5-ets-toeic-2018-test-4"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2019-test-2-ets-toeic-2018-test-3:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 36
      CRAWL_TO: 37
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 36 - 37 - ets-toeic-2019-test-2-ets-toeic-2018-test-3"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  crawl-ets-toeic-2019-test-3-ets-toeic-2019-test-1:
    docker:
      - image: cimg/base:2023.03
    environment:
      CRAWL_FROM: 38
      CRAWL_TO: 39
    steps:
      - install_java_package
      - checkout
      - run:
          name: "Crawl study 38 - 39 - ets-toeic-2019-test-3-ets-toeic-2019-test-1"
          command: |
            mvn clean install -DskipTests
            mvn test-compile compile
            mvn exec:java -Djava.util.concurrent.ForkJoinPool.common.parallelism=32
      - store_artifacts:
            path: ./

  upload-to-vps:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: "Upload to VPS"
          command: |
            ls
            #sudo apt-get install git python3 python3-pip -y
      - store_artifacts:
            path: ./

workflows:
  crawl-study-4:
    jobs:

      - crawl-ets-toeic-2019-test-10-ets-toeic-2022-test-10:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-4-ets-toeic-2022-test-9:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-5-ets-toeic-2021-test-5:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-8-ets-toeic-2020-test-6:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-7-ets-toeic-2020-test-7:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-6-ets-toeic-2020-test-8:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-10-ets-toeic-2020-test-9:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-1-ets-toeic-2019-test-8:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2021-test-2-ets-toeic-2022-test-5:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2018-test-5-ets-toeic-2019-test-9:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-1-ets-toeic-2021-test-1:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-4-ets-toeic-2019-test-6:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-2-ets-toeic-2021-test-4:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-3-ets-toeic-2019-test-7:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2020-test-3-ets-toeic-2021-test-3:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2022-test-2-ets-toeic-2018-test-2:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2019-test-4-ets-toeic-2018-test-1:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2019-test-5-ets-toeic-2018-test-4:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2019-test-2-ets-toeic-2018-test-3:
          filters:
            branches:
              only:
                - deployment

      - crawl-ets-toeic-2019-test-3-ets-toeic-2019-test-1:
          filters:
            branches:
              only:
                - deployment

      - upload-to-vps:
          requires:
            - ets-toeic-2019-test-10-ets-toeic-2022-test-10
            - ets-toeic-2020-test-4-ets-toeic-2022-test-9
            - ets-toeic-2020-test-5-ets-toeic-2021-test-5
            - ets-toeic-2022-test-8-ets-toeic-2020-test-6
            - ets-toeic-2022-test-7-ets-toeic-2020-test-7
            - ets-toeic-2022-test-6-ets-toeic-2020-test-8
            - ets-toeic-2020-test-10-ets-toeic-2020-test-9
            - ets-toeic-2022-test-1-ets-toeic-2019-test-8
            - ets-toeic-2021-test-2-ets-toeic-2022-test-5
            - ets-toeic-2018-test-5-ets-toeic-2019-test-9
            - ets-toeic-2020-test-1-ets-toeic-2021-test-1
            - ets-toeic-2022-test-4-ets-toeic-2019-test-6
            - ets-toeic-2020-test-2-ets-toeic-2021-test-4
            - ets-toeic-2022-test-3-ets-toeic-2019-test-7
            - ets-toeic-2020-test-3-ets-toeic-2021-test-3
            - ets-toeic-2022-test-2-ets-toeic-2018-test-2
            - ets-toeic-2019-test-4-ets-toeic-2018-test-1
            - ets-toeic-2019-test-5-ets-toeic-2018-test-4
            - ets-toeic-2019-test-2-ets-toeic-2018-test-3
            - ets-toeic-2019-test-3-ets-toeic-2019-test-1
